# Generated by Django 4.0 on 2022-11-17 23:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_infoperson_user_info_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoperson',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
