# Generated by Django 4.0 on 2022-11-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_manager_alter_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_user',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'User')], default='admin', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user'),
        ),
    ]
