# Generated by Django 4.0 on 2022-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_rol_user_alter_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol_user',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'User')], default='User', max_length=5),
        ),
    ]
