# Generated by Django 4.0 on 2022-11-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_rol_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='profile.png', null=True, upload_to='bicycle/')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('WT', 'Blanco'), ('BK', 'Negro'), ('RD', 'Rojo'), ('GN', 'Verde'), ('YW', 'Amarillo'), ('BL', 'AZUL'), ('GR', 'Blanco'), ('PK', 'Blanco')], default='WT', max_length=2)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge')], default='Medium', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rol_user',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bicyclemodels'),
        ),
    ]
