# Generated by Django 4.0 on 2022-11-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bicyclemodels_alter_user_rol_user_user_bicycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol_user',
        ),
    ]
