# Generated by Django 4.0 on 2022-11-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('accounts', '0009_remove_user_rol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.bicyclemodels'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.infoperson'),
        ),
        migrations.DeleteModel(
            name='BicycleModels',
        ),
        migrations.DeleteModel(
            name='InfoPerson',
        ),
    ]
