# Generated by Django 4.0 on 2022-11-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_rol_user'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUsersRolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.bikegroupsmodel')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.rolesmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
