# Generated by Django 4.0 on 2022-12-02 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_rolesmodel_groupusersrolmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikegroupsmodel',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
