# Generated by Django 4.0 on 2022-11-22 23:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='profile.png', null=True, upload_to='bicycle/')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('WT', 'Blanco'), ('BK', 'Negro'), ('RD', 'Rojo'), ('GN', 'Verde'), ('YW', 'Amarillo'), ('BL', 'AZUL'), ('GR', 'Blanco'), ('PK', 'Blanco')], default='WT', max_length=2)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge')], default='Medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=4)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
    ]
